#!/usr/bin/env bash
#
# revert_audit_fixes.sh — undo everything applied from audit_fixes.patch.
#
#   ./revert_audit_fixes.sh              # dry run: prints, changes nothing
#   ./revert_audit_fixes.sh --yes        # actually revert
#   ./revert_audit_fixes.sh --yes --keep-new-files
#
# Run it from the repository root.
#
# ORDER MATTERS AND IS NOT OBVIOUS
#     The retracted results are restored by a script that is ITSELF one of the
#     files being removed. So restoration happens first, deletion second. Get
#     this backwards and the 16 quarantined result files are stranded in
#     results/retracted/ with no tool left to move them back. (They would
#     still be recoverable by hand — nothing is ever deleted — but you would
#     have to know that.)
#
# WHAT THIS TOUCHES
#     1. restores quarantined results to their original locations
#     2. reverses the patch on 13 modified source files
#     3. deletes the 10 files that were added
#     4. removes artefacts generated by the new scripts
#
# WHAT THIS DELIBERATELY DOES NOT TOUCH
#     .env            — you may have added API_TOKENS / APPROVAL_DB_PATH.
#                       Editing someone's .env from a script is a good way to
#                       destroy a working key. Removal instructions printed at
#                       the end instead.
#     risk_model.pkl  — if you re-trained it (step 5), that model is BETTER
#                       than the one you started with: it matches your
#                       sklearn version. Reverting the code does not make the
#                       old version mismatch desirable again.
#     logs/, .venv/   — yours, not part of this change.

set -uo pipefail

DRY_RUN=1
KEEP_NEW=0
for arg in "$@"; do
    case "$arg" in
        --yes|-y)          DRY_RUN=0 ;;
        --keep-new-files)  KEEP_NEW=1 ;;
        -h|--help)         sed -n '2,40p' "$0"; exit 0 ;;
        *) echo "unknown option: $arg"; exit 1 ;;
    esac
done

say()  { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }
run()  {
    if [ "$DRY_RUN" -eq 1 ]; then
        printf '  would run: %s\n' "$*"
    else
        printf '  %s\n' "$*"
        eval "$@"
    fi
}

PATCH="${AUDIT_PATCH:-audit_fixes.patch}"

NEW_FILES=(
    "orchestrator/routing_policy.py"
    "agents/transaction_contract.py"
    "api/auth.py"
    "data/model_metadata.py"
    "scripts/fit_confidence_calibrators.py"
    "scripts/eval_rq4_coherence.py"
    "scripts/regenerate_all_evidence.py"
    "scripts/verify_audit_fixes.py"
    "tests/unit/test_audit_regressions.py"
    "FIXES.md"
    "results/retracted/RETRACTED.md"
)
# quarantine_invalid_results.py is NOT in the list above — it is removed
# separately, after it has been used to restore the results.

MODIFIED_FILES=(
    "agents/conversational_agent.py"
    "agents/payloads.py"
    "api/app.py"
    "api/approvals_router.py"
    "config/settings.py"
    "evaluation/results_io.py"
    "explainability/explainability_agent.py"
    "orchestrator/audit_log.py"
    "orchestrator/orchestrator.py"
    "orchestrator/planner.py"
    "scripts/eval_banking77_stratified.py"
    "scripts/eval_planner_vs_static.py"
    "tests/unit/test_full_advisory.py"
)

GENERATED=(
    "data/calibration"
    "results/superseded"
    "results/mock/calibration_risk_confidence.json"
    "results/groq/calibration_risk_confidence.json"
    "results/mock/_regeneration_manifest.json"
    "results/groq/_regeneration_manifest.json"
    "logs/audit/eval"
)

# -- sanity ------------------------------------------------------------
if [ ! -d "orchestrator" ] || [ ! -f "config/settings.py" ]; then
    echo "ERROR: run this from the repository root (no orchestrator/ here)."
    exit 1
fi

if [ "$DRY_RUN" -eq 1 ]; then
    printf '\n  DRY RUN — nothing will change. Re-run with --yes to apply.\n'
fi

# -- 1. restore quarantined results, BEFORE deleting the script --------
step "1/4  restoring quarantined results"
if [ -f "scripts/quarantine_invalid_results.py" ] && [ -d "results/retracted" ]; then
    PY="$(command -v python3 || command -v python)"
    if [ "$DRY_RUN" -eq 1 ]; then
        "$PY" scripts/quarantine_invalid_results.py --restore --dry-run 2>/dev/null \
            || say "(could not preview — will still attempt on --yes)"
    else
        "$PY" scripts/quarantine_invalid_results.py --restore \
            || say "WARNING: restore failed. Your files are still in "\
                   "results/retracted/ — move them back by hand before "\
                   "continuing. Nothing was deleted."
    fi
else
    say "nothing to restore (no results/retracted/, or script already gone)"
fi

# -- 2. reverse the source patch ---------------------------------------
step "2/4  reverting the 13 modified source files"
REVERTED=0

if [ -f "$PATCH" ] && git rev-parse --git-dir >/dev/null 2>&1; then
    if git apply -R --check "$PATCH" 2>/dev/null; then
        run "git apply -R '$PATCH'"
        REVERTED=1
    else
        say "patch will not reverse cleanly — you have edits on top of it."
        say "falling back to git history."
    fi
fi

if [ "$REVERTED" -eq 0 ] && git rev-parse --git-dir >/dev/null 2>&1; then
    # Find the commit before the fixes landed. APPLY.md step 0 asked for a
    # commit whose message contains "checkpoint before audit fixes"; fall
    # back to asking the user rather than guessing at a SHA, because
    # checking out the wrong commit over 13 files is worse than stopping.
    BASE="$(git log --format='%H %s' | grep -i 'checkpoint before audit fixes' | head -1 | cut -d' ' -f1)"
    if [ -n "$BASE" ]; then
        say "found pre-fix commit ${BASE:0:8}"
        for f in "${MODIFIED_FILES[@]}"; do
            run "git checkout '$BASE' -- '$f'"
        done
        REVERTED=1
    fi
fi

if [ "$REVERTED" -eq 0 ]; then
    say "COULD NOT REVERT AUTOMATICALLY."
    say "No usable $PATCH and no commit matching 'checkpoint before audit fixes'."
    say "Options:"
    say "  - set AUDIT_PATCH=/path/to/audit_fixes.patch and re-run"
    say "  - git checkout <your-pre-fix-commit> -- ${MODIFIED_FILES[*]}"
    say "  - re-extract the 13 files from your original zip"
    say ""
    say "Stopping here. Steps 3 and 4 are skipped: deleting the new modules"
    say "while the modified files still import them would leave the tree"
    say "unable to start at all."
    exit 2
fi

# -- 3. remove the added files -----------------------------------------
step "3/4  removing added files"
if [ "$KEEP_NEW" -eq 1 ]; then
    say "--keep-new-files given; leaving them in place."
    say "NOTE: these are now dead code. Nothing imports them once the"
    say "      modified files are reverted."
else
    for f in "${NEW_FILES[@]}"; do
        [ -e "$f" ] && run "rm -f '$f'" || say "already absent: $f"
    done
    # last, now that it has done its job in step 1
    [ -e "scripts/quarantine_invalid_results.py" ] \
        && run "rm -f 'scripts/quarantine_invalid_results.py'"
    [ -d "results/retracted" ] && run "rmdir 'results/retracted' 2>/dev/null || true"
fi

# -- 4. remove generated artefacts -------------------------------------
step "4/4  removing artefacts generated by the new scripts"
for g in "${GENERATED[@]}"; do
    [ -e "$g" ] && run "rm -rf '$g'" || true
done

# -- verify ------------------------------------------------------------
step "verification"
if [ "$DRY_RUN" -eq 1 ]; then
    say "(dry run — nothing checked)"
else
    PY="$(command -v python3 || command -v python)"
    if "$PY" -c "import orchestrator.orchestrator, explainability.explainability_agent" 2>/dev/null; then
        say "OK: the package imports cleanly."
    else
        say "PROBLEM: the package no longer imports."
        say "Most likely a modified file did not revert and still references"
        say "a module that has just been deleted. Check with:"
        say "  git status"
        say "  python -c 'import orchestrator.orchestrator'"
    fi
    if grep -rqs "routing_policy\|transaction_contract\|model_metadata" \
        --include="*.py" orchestrator agents api config evaluation explainability scripts tests 2>/dev/null; then
        say "WARNING: something still references a removed module:"
        grep -rns "routing_policy\|transaction_contract\|model_metadata" \
            --include="*.py" orchestrator agents api config evaluation explainability scripts tests 2>/dev/null \
            | head -10 | sed 's/^/         /'
    fi
fi

# -- manual leftovers --------------------------------------------------
cat <<'EOF'

== left for you to do by hand

  .env — remove these if you added them, they are now inert:
      API_AUTH_ENABLED, API_TOKENS, API_RATE_LIMIT_PER_MIN
      APPROVAL_DB_PATH, MEMORY_DB_PATH, RISK_STRICT_MODEL_VERSION

  data/processed/risk_model.meta.json — left in place on purpose. It is
  harmless without the code that reads it, and if you re-trained the model
  it records which sklearn version produced the pickle you are now using.
  Delete it only if you also restored the original risk_model.pkl.

  Run your test suite and compare the failure list against the baseline you
  took before applying:
      python -m pytest tests/unit -q

EOF

if [ "$DRY_RUN" -eq 1 ]; then
    printf '  DRY RUN complete. Re-run with --yes to apply.\n\n'
else
    printf '  Revert complete.\n\n'
fi
